backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "tours"
    label: "Tours"
    folder: "src/content/tours"
    create: true
    slug: "{{year}}"
    fields:
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Venue", name: "venue", widget: "string" }
      - { label: "Captain", name: "captain", widget: "string" }
      - { label: "Dates", name: "dates", widget: "string" }
      - { label: "Highlights", name: "highlights", widget: "text", required: false }
